# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GerenciadorArquivos_config = debug

else ifeq ($(config),release)
  GerenciadorArquivos_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GerenciadorArquivos

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GerenciadorArquivos:
ifneq (,$(GerenciadorArquivos_config))
	@echo "==== Building GerenciadorArquivos ($(GerenciadorArquivos_config)) ===="
	@${MAKE} --no-print-directory -C . -f GerenciadorArquivos.make config=$(GerenciadorArquivos_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GerenciadorArquivos.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GerenciadorArquivos"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"